---
resource_types:
- name: postgres-table
  type: docker-image
  source:
    repository: kopptr/postgres-resource

resources:
   - name: five-thirtyeight-data
     type: git
     source:
        branch: master
        uri: https://github.com/fivethirtyeight/data.git
   - name: example-ds-pipeline
     type: git
     source:
        branch: master
        uri: https://github.com/kopptr/example-ds-pipeline.git
   - name: ticket_prices_table
     type: postgres-table
     source:
        base_name: ticket_prices
        uri: ((postgres_url))

jobs:
  - name: load-database
    plan:
       - aggregate:
          - get: example-ds-pipeline
            trigger: true
          - get: five-thirtyeight-data
            trigger: true
       - task: create-and-copy-csv
         config:
            platform: linux
            image_resource:
               type: docker-image
               source: {repository: kopptr/postgres-resource}
            inputs:
               - name: five-thirtyeight-data
               - name: example-ds-pipeline
            params:
               URL: ((postgres_url))
            run:
               path: example-ds-pipeline/bin/load-db.sh
       - put: ticket_prices_table
