---
resources:
   - name: five-thirtyeight-data
     type: git
     source:
        branch: master
        uri: https://github.com/fivethirtyeight/data.git
   - name: example-ds-pipeline
     type: git
     source:
        branch: master
        uri: https://github.com/kopptr/example-ds-pipeline.git

jobs:
   - name: print-first-bytes
     plan:
        - aggregate:
           - get: example-ds-pipeline
             trigger: true
           - get: five-thirtyeight-data
             trigger: true
        - task: print-first-50-bytes
          config:
             platform: linux
             image_resource:
                type: docker-image
                source: {repository: ubuntu}
             inputs:
                - name: five-thirtyeight-data
             run:
                path: head
                args: ["-c", "80", "five-thirtyeight-data/nfl-ticket-prices/2014-average-ticket-price.csv"]
