---
resources:
   - name: nfl-ticket-prices-raw
     type: git
     source:
        branch: master
        uri: https://github.com/fivethirtyeight/data/tree/master/nfl-ticket-prices

   - name: example-ds-pipeline
     type: git
     source:
        branch: master
        uri: https://github.com/kopptr/example-ds-pipeline.git

jobs:
   - name: print-first-lines
     plan:
        - aggregate:
           - get: example-ds-pipeline
             trigger: true
           - get: nfl-ticket-prices-raw
             trigger: true
        - task: print-first-5-lines
          config:
             platform: linux
             image_resource:
                type: docker-image
                source: {repository: ubuntu}
          run:
             path: cat
             args: ["-n", "5", "nfl-ticket-prices-raw/2014-average-ticket-price.csv"]
